# Generated by Django 3.2.3 on 2021-06-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blobfile',
            name='file',
            field=models.FileField(upload_to='files/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='blobimage',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m/%d/'),
        ),
    ]
