# Generated by Django 3.2.3 on 2021-06-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0002_auto_20210604_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blobfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='blobimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
