# Generated by Django 3.2.3 on 2021-06-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0003_auto_20210608_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blobfile',
            name='file',
            field=models.FileField(null=True, upload_to='files/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='blobimage',
            name='image',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
