# Generated by Django 3.2.3 on 2021-06-30 13:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blob', '0004_auto_20210616_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='blobfile',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 13, 56, 39, 524548, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='blobfile',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 13, 56, 39, 524575, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='blobimage',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 13, 56, 39, 523491, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='blobimage',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 13, 56, 39, 523542, tzinfo=utc)),
        ),
    ]
